version: '3.3'
services:
  app:
    command: sh -c "mvn package && java -jar target/app.jar"
    expose:
      - 80
    image: maven:3.6.3-openjdk-11
    volumes:
      - ~/.m2:/root/.m2
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
    working_dir: /app
  prometheus:
    image: prom/prometheus:v2.19.3
    ports:
    - 9090:9090
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
